before:
  hooks:
    - go mod tidy
builds:
- env:
    - CGO_ENABLED=0
  mod_timestamp: '{{ .CommitTimestamp }}'
  flags:
    - -trimpath
  ldflags:
    - '-s -w'
  goos:
    - windows
    - linux
    - darwin
  goarch:
    - amd64
    - arm64
    - '386'
  ignore:
    - goos: darwin
      goarch: '386'
    - goos: linux
      goarch: '386'
  binary: '{{ .ProjectName }}'
archives:
- format: zip
  name_template: '{{ .ProjectName }}_{{ .Version }}_{{ .Os }}_{{ .Arch }}'
checksum:
  name_template: '{{ .ProjectName }}_{{ .Version }}_SHA256SUMS'
  algorithm: sha256
snapshot:
  name_template: '{{ incpatch .Version }}-devel'
changelog:
  sort: asc
  filters:
    exclude:
    - '^docs:'
    - '^test:'
