description: Root of the bundle config
children:
  bundle:
    description: |
      Bundle contains details about this bundle, such as its name,
      version of the spec (TODO), default cluster, default warehouse, etc.
    children:
      environment:
        description: Environment is set by the mutator that selects the environment.

  artifacts:
    description: Artifacts contains a description of all code artifacts in this bundle.
