name: shell-into-github-env

on:
  pull_request:
    types: [opened, synchronize, reopened]

jobs:
  tests:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository and submodules
        uses: actions/checkout@v2
        with:
          token:  ${{ secrets.DECO_GITHUB_TOKEN }}
          submodules: recursive

      - name: Unshallow
        run: git fetch --prune --unshallow

      - name: Setup Go
        uses: actions/setup-go@v3
        with:
          go-version: 1.18.x
          cache: true

      - name: Set go env
        run: |
          echo "GOPATH=$(go env GOPATH)" >> $GITHUB_ENV
          echo "$(go env GOPATH)/bin" >> $GITHUB_PATH
          go install gotest.tools/gotestsum@latest
          go install honnef.co/go/tools/cmd/staticcheck@latest

      - name: Pull external libraries
        run: make vendor

      - name: Setup tmate session
        uses: mxschmitt/action-tmate@v3
