name: publish-winget

on:
  workflow_dispatch:

jobs:
  publish-to-winget-pkgs:
    runs-on: windows-latest
    environment: release
    steps:
      - uses: vedantmgoyal2009/winget-releaser@3659f24b3c6cafe2c0eb0f926d849a4888d2958b # Latest commit on June 25, 2024
        with:
          identifier: Databricks.DatabricksCLI
          installers-regex: 'windows_.*-signed\.zip$' # Only signed Windows releases
          token: ${{ secrets.ENG_DEV_ECOSYSTEM_BOT_TOKEN }}
          fork-user: eng-dev-ecosystem-bot
