name: publish-latest

on:
  workflow_dispatch:

  workflow_call:

jobs:
  publish:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          ref: release-s3

      - name: Install s3cmd
        run: |
          sudo apt-get update
          sudo apt-get install s3cmd

      - name: Merge release branch
        run: |
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git config --global user.name "github-actions[bot]"
          git merge origin/release-s3

      - name: Publish to S3
        working-directory: ./scripts
        run: ./publish_to_s3.sh
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
